# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(198, 238)
        Dialog.setToolTip("")
        Dialog.setStyleSheet("text-align:center;")
        self.lineAddress = QtWidgets.QLineEdit(Dialog)
        self.lineAddress.setGeometry(QtCore.QRect(10, 10, 181, 22))
        self.lineAddress.setTabletTracking(False)
        self.lineAddress.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.lineAddress.setAcceptDrops(True)
        self.lineAddress.setWhatsThis("")
        self.lineAddress.setAccessibleDescription("")
        self.lineAddress.setStyleSheet("border: 1px solid black; \n"
"border-radius:5px;")
        self.lineAddress.setText("")
        self.lineAddress.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineAddress.setDragEnabled(False)
        self.lineAddress.setReadOnly(False)
        self.lineAddress.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineAddress.setObjectName("lineAddress")
        self.lineLoginAPI = QtWidgets.QLineEdit(Dialog)
        self.lineLoginAPI.setGeometry(QtCore.QRect(10, 100, 181, 22))
        self.lineLoginAPI.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.lineLoginAPI.setStyleSheet("border: 1px solid black; \n"
"border-radius:5px;")
        self.lineLoginAPI.setText("")
        self.lineLoginAPI.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        # self.lineLoginAPI.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineLoginAPI.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineLoginAPI.setPlaceholderText("Login API")
        self.lineLoginAPI.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineLoginAPI.setObjectName("lineLoginAPI")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 190, 121, 21))
        self.label.setObjectName("label")
        self.startButton = QtWidgets.QPushButton(Dialog)
        self.startButton.setGeometry(QtCore.QRect(10, 140, 81, 41))
        self.startButton.setStyleSheet("background-color: #e3e0de;\n"
"border: 1px solid black; \n"
"border-radius:5px;")
        self.startButton.setObjectName("startButton")
        self.resetButton = QtWidgets.QPushButton(Dialog)
        self.resetButton.setGeometry(QtCore.QRect(110, 140, 81, 41))
        self.resetButton.setStyleSheet("background-color: #e3e0de;\n"
"border: 1px solid black; \n"
"border-radius:5px;")
        self.resetButton.setObjectName("resetButton")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 210, 191, 21))
        self.label_2.setObjectName("label_2")
        self.lineLogin = QtWidgets.QLineEdit(Dialog)
        self.lineLogin.setGeometry(QtCore.QRect(10, 70, 181, 22))
        self.lineLogin.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.lineLogin.setStyleSheet("border: 1px solid black; \n"
"border-radius:5px;")
        self.lineLogin.setText("")
        self.lineLogin.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineLogin.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineLogin.setObjectName("lineLogin")
        self.linePort = QtWidgets.QLineEdit(Dialog)
        self.linePort.setGeometry(QtCore.QRect(40, 40, 121, 22))
        self.linePort.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.linePort.setStyleSheet("border: 1px solid black; \n"
"border-radius:5px;")
        self.linePort.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.linePort.setObjectName("linePort")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "EDR"))
        self.lineAddress.setToolTip(_translate("Dialog", "<html><head/><body><p style=\"border: 1px solid #7a7b7e; border-radius:5px; text-align: center;\"><br/></p></body></html>"))
        self.lineAddress.setPlaceholderText(_translate("Dialog", "ip address"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">connection:</span></p></body></html>"))
        self.startButton.setText(_translate("Dialog", "Start"))
        self.resetButton.setText(_translate("Dialog", "Reset"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">нет соединенния</span></p></body></html>"))
        self.lineLogin.setPlaceholderText(_translate("Dialog", "Login"))
        self.linePort.setToolTip(_translate("Dialog", "<html><head/><body><p style=\"border: 1px solid #7a7b7e; border-radius:5px;\"><br/></p></body></html>"))
        self.linePort.setPlaceholderText(_translate("Dialog", "port"))
